version: '3'
services:
  web:
    build: .
    command: ["./wait-for", "db:3306", "--", "python", "app.py"]
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'wydatki'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:

